name: tuneyverse
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dropdown_button2: ^2.3.9
  font_awesome_flutter: ^10.7.0
  video_player: ^2.8.2
  cupertino_icons: ^1.0.8
  file_picker: ^6.2.0
  flutter_dropzone: ^3.0.5
  flutter_sound: ^9.1.0
  just_audio: ^0.9.37
  flutter_svg: ^2.0.10
  audio_waveforms: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Regular.ttf

  assets:
    - assets/videos/vid1.mp4
    - assets/videos/vid2.mp4
    - assets/videos/vid3.mp4
    - assets/images/logo.png
    - assets/images/img1.png
    - assets/images/img2.png
    - assets/images/img3.png
    - assets/images/img4.png
    - assets/images/img5.png
    - assets/images/img6.png
    - assets/images/innovate1.png
    - assets/images/innovate2.png
    - assets/images/innovate3.png
    - assets/icons/dj.png
    - assets/icons/mic.png
    - assets/icons/rec.png
    - assets/icons/vid.png
    - assets/images/upload_image.png
    - assets/images/select_image.png
    - assets/images/download_image.png
    - assets/video_preview.mp4
    - assets/hero_about.png
    - assets/about_main.png
    - assets/team.png
    - assets/why_choose.png
    - assets/mission_vision.png
    - assets/contact_us.png
    - assets/icons/facebook.svg
    - assets/icons/x.svg
    - assets/icons/link-alt.svg
    - assets/icons/linkedin.svg
